# 指定运行端口
server:
  port: 8101

# 指定服务名称
spring:
  application:
    name: eureka-client

eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
#      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka
      defaultZone: http://root:root@localhost:8004/eureka
      enabled: true # 启用eureka客户端
      registry-fetch-interval-seconds: 30 #定义去eureka服务端获取服务列表的时间间隔